# Generated by Django 3.2.6 on 2022-12-13 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ASIN', models.CharField(max_length=10)),
                ('SKU', models.CharField(max_length=10)),
                ('AmazonOrderItemCode', models.CharField(max_length=15)),
                ('NumberOfItems', models.IntegerField()),
                ('ProductName', models.CharField(max_length=200)),
                ('Quantity', models.IntegerField()),
                ('ItemStatus', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
    ]
